### ISSUE TITLE
correct Normative definition of JSON

### ISSUE THREAD

**Issue by allenwb** [tc39/proposal-json-superset#1]
ECMA and TC39 considers the normative definition of JSON to be ECMA-404 (which is being fast-tracked as an ISO standard) rather than RFC 7159.

**Comment by gibson042** [comment]
RFCs are immutable by definition... is ECMA-404? If not, there's a risk of future disruption. Regardless, it only appears in the explainer so I will update.

**Comment by gibson042** [comment]
Ah, we're probably good.
> Because it is so simple, it is not expected that the JSON grammar will ever change.

> A description of JSON in ECMAScript terms appears in Version 5.1 of the ECMAScript specification [[ECMA-262](https://tools.ietf.org/html/rfc7159#ref-ECMA-262)], Section 15.12. JSON is also described in [[ECMA-404](https://tools.ietf.org/html/rfc7159#ref-ECMA-404)].
> 
> All of the specifications of JSON syntax agree on the syntactic elements of the language.

**Comment by allenwb** [comment]
Actually, ECMA-404 exists because at one time the IETF JSON working group  was talking about the possibility of making some syntactic changes to their JSON specification.
