### ISSUE TITLE
The case of duplicate "__proto__" key

### ISSUE THREAD

**Issue by claudepache** [tc39/proposal-json-superset#3]
The following is valid JSON, but will trigger an early SyntaxError when interpreted as object literal in implementations implementing Annex B (see [[1]](https://tc39.github.io/ecma262/#sec-__proto__-property-names-in-object-initializers)):
```json
{ "__proto__": 1, "__proto__": 2 }
```

**Comment by gibson042** [comment]
True, but how is that an issue? `{ "__proto__": 1, "__proto__": 2 }` is syntactically valid ECMAScript with or without this proposal, and is only semantically invalid under Annex B. And although it's beside the point, [RFC 7159 section 4](https://tools.ietf.org/html/rfc7159#section-4) explicitly addresses such cases in the context of JSON:
> When the names within an object are not unique, the behavior of software that receives such an object is unpredictable.

**Comment by claudepache** [comment]
> True, but how is that an issue?

I don’t know (since I don’t consider the current difference around U+2028 and U+2029 to be an issue either, to begin with). Just wanted to make sure you’re aware.

**Comment by gibson042** [comment]
OK, I'll add a note.
