### ISSUE TITLE
Stage 3 review

### ISSUE THREAD

**Issue by mathiasbynens** [tc39/proposal-json-superset#7]
Reviewers:

- [x] @michaelficarra
- [x] @ljharb

**Comment by ljharb** [comment]
A quick one to review :-) LGTM

**Comment by michaelficarra** [comment]
I see the proposal has removed the alternative definition of `DoubleStringCharacters` for use in `JSON.parse`. That should be reverted. This alternative definition is still needed, as no ASCII control characters are allowed in JSON strings. The first sentence can be deleted, since it will not longer be accurate.

**Comment by mathiasbynens** [comment]
Right, the “or U+0000 through U+001F” part is still important. Good catch, @michaelficarra!

**Comment by michaelficarra** [comment]
It's a bit weird that `"<U+2028>"` creates `"\u2028"` but `"\<U+2028>"` creates an empty string. But I think it's okay.

**Comment by michaelficarra** [comment]
LGTM otherwise.

**Comment by mathiasbynens** [comment]
@erights voiced strong opposition for changing U+2028 and U+2029 anywhere else, so I doubt we can change `LineContinuation`. Mark?

**Comment by michaelficarra** [comment]
@mathiasbynens It would be a change in the SV of LineContinuation, not the grammar. But yes, the same security argument from @erights demands we leave that unchanged.

**Comment by mathiasbynens** [comment]
(After discussing this offline with @michaelficarra, it could be either, although IMHO changing the grammar would be the simpler change.)

**Comment by michaelficarra** [comment]
Just to be clear, I do not think we should change the SV of a backslash followed by U+2028/U+2029. It would possibly introduce security issues. Also, we likely cannot change the grammar to disallow backslash followed by U+2028/U+2029, but I'd love to see usage numbers on that.

**Comment by mathiasbynens** [comment]
Yes, agreed. We were both talking hypothetically :)

**Comment by gibson042** [comment]
> I see the proposal has removed the alternative definition of `DoubleStringCharacters` for use in `JSON.parse`. That should be reverted. This alternative definition is still needed, as no ASCII control characters are allowed in JSON strings.

@michaelficarra The removal was intentional. We don't need it because step 2 of JSON.parse already specifies a SyntaxError if the text is not valid ECMA-404 JSON.

**Comment by michaelficarra** [comment]
@gibson042 Okay, that should work. LGTM.

**Comment by mathiasbynens** [comment]
Closing this issue as both @ljharb and @michaelficarra gave their blessing.
