### ISSUE TITLE
Test262 missing

### ISSUE THREAD

**Issue by adrianheine** [tc39/proposal-json-superset#9]
As far as I see it there are no test262 tests for this proposal.

**Comment by mathiasbynens** [comment]
Do you want to give it a go, @adrianheine? :)

**Comment by mathiasbynens** [comment]
It’s a matter of updating these files:

* https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.3.js
* https://github.com/tc39/test262/blob/master/test/language/line-terminators/S7.3_A2.4.js

…or maybe removing them and adding new ones in their stead.

**Comment by mathiasbynens** [comment]
PR: https://github.com/tc39/test262/pull/1543
